name: Continuous Integration
on:
  push:
    branches:
      - master
      - actions-*
    tags:
      - v*
  pull_request:
env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
jobs:
  specs:
    name: ${{ matrix.job }} ruby-${{ matrix.combo.ruby || matrix.ruby }} ${{ matrix.combo.activesupport && format('activesupport-{0}', matrix.combo.activesupport) }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        combo:
          - activesupport: "latest"
            ruby: "3.0"
          - activesupport: "6.1"
            ruby: "2.7"
          - activesupport: "6.0"
            ruby: "2.7"
          - activesupport: "5.2"
            ruby: "2.6"
          - activesupport: "5.1"
            ruby: "2.6"
          - activesupport: "5.0"
            ruby: "2.5"
          - activesupport: "4.2"
            ruby: "2.5"
            bundler: "1.17.3"
        job: [ rspec ]
        include:
          - job: "standardrb"
            ruby: "2.7"
          - job: "coverage"
            ruby: "3.0"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby ${{ matrix.combo.ruby || matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.combo.ruby || matrix.ruby }}
      - name: setup bundler
        run: |
          if [ "${{ matrix.combo.bundler }}" != "" ]; then
            gem uninstall bundler --all
            gem install bundler --no-document --version ${{ matrix.combo.bundler }}
          fi
          if [ "${{ matrix.combo.activesupport }}" != "" ] && [ "${{ matrix.combo.activesupport }}" != "latest" ]; then
            echo "using gemfile gemfiles/activesupport_${{ matrix.combo.activesupport }}.gemfile"
            bundle config set gemfile "gemfiles/activesupport_${{ matrix.combo.activesupport }}.gemfile"
          fi
          bundle update
      - name: specs
        if:   matrix.job == 'rspec'
        run:  bundle exec rake spec
      - name: code coverage
        if:   matrix.job == 'coverage'
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: TODO
        with:
          coverageCommand: bundle exec rake spec
      - name: standardrb
        if:   matrix.job == 'standardrb'
        run:  bundle exec rake standard
